#!/usr/bin/env ruby
require 'highline/import'


menu_prompt = <<EOS
1. Add a scenario
2. List all scenarios
3. Exit
EOS

def print_error_message
  puts "[Help] Run as: ./would_you_rather manage"
end

if ARGV.length < 1
  print_error_message
elsif ARGV.length == 1
  # Not valid argument
  if ARGV[0] != 'manage'
    print_error_message
  else
    choose do |menu|
      menu.prompt = ""

      menu.choice('Add a scenario') { say("") }
      menu.choice('List all scenarios') { say("No scenarios found. Add a scenario.\n") }
      menu.choice('Exit') { say("Peace Out!\n") }
    end
  end
end
