#!/usr/bin/env ruby
require 'highline/import'


menu_prompt = <<EOS
1. Add a scenario
2. List all scenarios
3. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
  choose do |menu|
    menu.prompt = ""

    menu.choice('Add a scenario') { say("") }
    menu.choice('List all scenarios') { say("No scenarios found. Add a scenario.\n") }
    menu.choice('Exit') { say("Peace Out!\n") }
  end
else
  puts "[Help] Run as: ./would_you_rather manage"
end
