#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

menu_prompt = <<EOS
1. Add a currency
2. List all currencies
3. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
  choose do |menu|
    menu.prompt = ""

    scenarios_controller = ScenariosController.new
    menu.choice('Add a currency') { say("") }
    menu.choice('List all currencies') { scenarios_controller.index }
    menu.choice('Exit') { say("Signed out!\n") }
  end
else
  puts "[Help] Run as: ./would_you_rather manage"
end
